### ISSUE TITLE
Add screenshots to readme

### ISSUE THREAD

**Issue by GroovinChip** [josat799/flutter-multi-wizard#1]
It would be nice to see what this looks like

**Comment by josat799** [comment]
Hi @GroovinChip!

Thanks for reaching out. 
I did this plugin as a project to a course and did not think that anyone would find it. 

The latest push adds support for null-safety, example code, and a GIF showing how the plugin could be used.

Feel free to reach out if you have anymore questions or if find the plugin useful :)
